use_frameworks!

# ignore all warnings from all dependencies
#inhibit_all_warnings!

target 'StepperView_Example' do
  platform :ios, '13.0'
  pod 'StepperView', :path => '../'

  target 'StepperView_Tests' do
    inherit! :search_paths
    pod 'SnapshotTesting', '~> 1.7.2', :inhibit_warnings => true
  end
end

target 'StepperView_Watch' do
  platform :watchos, '7.0'
  pod 'StepperView', :path => '../'
end

target 'StepperView_Watch Extension' do
  platform :watchos, '7.0'
  pod 'StepperView', :path => '../'
end
