use_frameworks!

# ignore all warnings from all dependencies
#inhibit_all_warnings!

target 'StepperView_Example' do
  pod 'StepperView', :path => '../'

  target 'StepperView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
  end
end
