module: StepperView
module_version: 2.0
author: Badarinath Venkatnarayansetty
author_url: https://github.com/badrinathvm
github_url: https://github.com/badrinathvm/StepperView
root_url: https://badrinathvm.github.io/StepperView/

source_directory: .
swift_build_tool: spm

output: docs
clean: true
theme: apple

min_acl: public
